services:
  magicalauthdb:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ENCRYPTION_SECRET}
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  magicalauth:
    image: ghcr.io/devxt-llc/magicalauth:main
    init: true
    depends_on:
      - magicalauthdb
    environment:
      APP_NAME: ${APP_NAME}
      ALLOWED_DOMAINS: ${ALLOWED_DOMAINS}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      MAGICALAUTH_SERVER: ${MAGICALAUTH_SERVER}
      MAGIC_LINK_URL: ${MAGIC_LINK_URL}
      REGISTRATION_WEBHOOK: ${REGISTRATION_WEBHOOK}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      DATABASE_TYPE: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: magicalauthdb
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${ENCRYPTION_SECRET}
      UVICORN_WORKERS: 5
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: always
    ports:
      - 12437:12437
      - 8519:8519