version: "3.7"
services:
  magicalauthdb:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ENCRYPTION_SECRET}
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  magicalauth:
    image: ghcr.io/devxt-llc/magicalauth:main
    init: true
    depends_on:
      - magicalauthdb
    environment:
      APP_NAME: ${APP_NAME}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      DATABASE_TYPE: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: magicalauthdb
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${ENCRYPTION_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      MAGIC_LINK_URL: ${MAGIC_LINK_URL}
      MAGICALAUTH_SERVER: ${MAGICALAUTH_SERVER}
      REGISTRATION_WEBHOOK: ${REGISTRATION_WEBHOOK}
      UVICORN_WORKERS: 5
      LOGLEVEL: INFO
    restart: always
    ports:
      - 12437:12437
      - 8519:8519