name: Build and Test

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-magicalauth:
    uses: josh-xt/AGiXT/.github/workflows/operation-docker-build-publish.yml@main
    with:
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64/v8
      registry-dockerhub-enable: false
  test-magicalauth:
    uses: josh-xt/AGiXT/.github/workflows/operation-test-with-jupyter.yml@main
    with:
      notebook: tests.ipynb
      image: ${{ needs.build-magicalauth.outputs.primary-image }}
      port: "14374"
      additional-python-dependencies: pyotp requests qrcode
    needs: build-magicalauth
